# Generated by Django 4.2.4 on 2023-09-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newss',
            name='desc',
            field=models.TextField(),
        ),
    ]
